const StateToId = {
	"Kerala": "IN-KL",
	"Telengana": "IN-TG",
	"Delhi": "IN-DL",
	"Rajasthan": "IN-RJ",
	"Uttar Pradesh": "IN-UP",
	"Haryana": "IN-HR",
	"Ladakh": "Ladakh",
	"Tamil Nadu": "IN-TN",
	"Karnataka": "IN-KA",
	"Maharashtra": "IN-MH",
	"Punjab": "IN-PB",
	"Jammu and Kashmir": "IN-JK",
	"Andhra Pradesh": "IN-AP",
	"Uttarakhand": "IN-UT",
	"Odisha": "IN-OR",
	"Puducherry": "IN-PY",
	"West Bengal": "IN-WB",
	"Chhattisgarh": "IN-CT",
	"Chandigarh": "IN-CH",
	"Gujarat": "IN-GJ",
	"Himachal Pradesh": "IN-HP",
	"Madhya Pradesh": "IN-MP",
	"Bihar": "IN-BR",
	"Manipur": "IN-MN",
	"Mizoram": "IN-MZ",
	"Andaman and Nicobar Islands": "IN-AN",
	"Goa": "IN-GA",
	"Unassigned": "Unassigned",
	"Assam": "IN-AS",
	"Jharkhand": "IN-JH",
	"Arunachal Pradesh": "IN-AR",
	"Tripura": "IN-TR",
	"Nagaland": "IN-NL",
	"Meghalaya": "IN-ML",
	"Dadra and Nagar Haveli and Daman and Diu": "IN-DN",
	"Cases being reassigned to states": "reassigned",
	"Sikkim": "IN-SK",
	"Daman & Diu": "IN-DD",
	"Lakshadweep": "IN-LD",
	"Telangana": "IN-TG",
	"Dadra and Nagar Haveli": "IN-DN",
	"Bihar****": "IN-BR"
}
 const IdToState = {
	"Kerala": "IN-KL",
	"IN-TG": "Telengana",
	"IN-DL": "Delhi",
	"IN-RJ": "Rajasthan",
	"IN-UP": "Uttar Pradesh",
	"IN-HR": "Haryana",
	"Ladakh": "Ladakh",
	"IN-TN": "Tamil Nadu",
	"IN-KA": "Karnataka",
	"IN-MH": "Maharashtra",
	"IN-PB": "Punjab",
	"IN-JK": "Jammu and Kashmir",
	"IN-AP": "Andhra Pradesh",
	"IN-UT": "Uttarakhand",
	"IN-OR": "Odisha",
	"IN-PY": "Puducherry",
	"IN-WB": "West Bengal",
	"IN-CT": "Chhattisgarh",
	"IN-CH": "Chandigarh",
	"IN-GJ": "Gujarat",
	"IN-HP": "Himachal Pradesh",
	"IN-MP": "Madhya Pradesh",
	"IN-BR": "Bihar",
	"IN-MN": "Manipur" ,
	"IN-MZ": "Mizoram",
	"IN-AN": "Andaman and Nicobar Islands",
	"IN-GA": "Goa",
	"Unassigned": "Unassigned",
	"IN-AS": "Assam",
	"IN-JH": "Jharkhand",
	"Arunachal Pradesh": "IN-AR",
	"IN-TR": "Tripura",
	"IN-NL": "Nagaland",
	"IN-ML": "Meghalaya",
	"IN-DN": "Dadra and Nagar Haveli and Daman and Diu",
	"reassigned": "Cases being reassigned to states",
	"IN-SK": "Sikkim",
	"IN-DD": "Daman & Diu",
	"IN-LD": "Lakshadweep",
	"IN-TG": "Telangana",
	"IN-DN": "Dadra and Nagar Haveli",
	"IN-BR": "Bihar****",
} 